apiVersion: extensions/v1beta1
kind: Job
metadata:
  name: backup
spec:
  selector:
    matchLabels:
      name: backup
  parallelism: 1
  completions: 1
  activeDeadlineSeconds: 100
  template:
    metadata:
      name: backup
      labels:
        name: backup
    spec:
      containers:
      - name: backup
        image: openshift3/mysql-55-rhel7
        command:
          - /bin/bash
          - -c
          - mysqldump --opt -hmysql -u"${MYSQL_USER}" -p"${MYSQL_PASSWORD}" ${MYSQL_DATABASE}
        env:
          - name: MYSQL_USER
            valueFrom:
              configMapKeyRef:
                name: mysql-access
                key: user
          - name: MYSQL_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: mysql-access
                key: password
          - name: MYSQL_DATABASE
            valueFrom:
              configMapKeyRef:
                name: mysql-access
                key: database
      restartPolicy: Never
