* MySQL Backup job example

Simple application to demonstrate how to run a job to backup MySQL

Start to deploy with ./deploy.sh (it would cleanup previous instance)

Start backuping with ./backup.sh

** Note :

- The backup script just output to the output, you can do whatever you like with
  it like putting it to a shared volume or object storage (i.e: s3, swift)

- The Job definition in kubernetes doesn't support currently (planned in 1.4) scheduling so you
  have to resort to to the good ol cron to schedule those tasks to run the
  */backup.sh/*

- I do some fancy things with configmaps to store variables provided by the
  templates parameters and get used after to the containers and jobs. Ideally
  this should have been a secrets but there is no way to encore in base64 in a
  template. Moreover the execNewPod post action script doesn't use the configmap but
  the template parameters directly cause this does not seem to work there. Oh
  well at least jobs does not need to have hardcoded value and can use the
  configmaps parameters.

* Contact

Chmouel Boudjnah <chmouel@redhat.com>
